version: '3.8'

services:
  frontend:
    image: geyasreer/3-tier-frontend:0.1  # ← Your pushed image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api/todos
    depends_on:
      - backend
    networks:
      - todo-network

  backend:
    image: geyasreer/3-tier-backend:0.1  # ← Your pushed image
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/todoapp
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge