apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: todo-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-app
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: geyasreer/3-tier-frontend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://backend-service:5000/api/todos"
        ports:
        - containerPort: 3000