apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: todo-app
    tier: frontend
spec:
  type: ClusterIP  # Use NodePort for bare metal
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: todo-app
    tier: frontend