apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: todo-app
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      tier: database
  template:
    metadata:
      labels:
        app: todo-app
        tier: database
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc