apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: todo-app
    tier: database
spec:
  clusterIP: None  # Headless service for direct pod access
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app: todo-app
    tier: database