apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: todo-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-app
        tier: backend
    spec:
      containers:
      - name: backend
        image: geyasreer/3-tier-backend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/todoapp"
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30