apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: todo-app
    tier: backend
spec:
  type: ClusterIP  # Internal service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: todo-app
    tier: backend